---

- name: Manage Ruby environment
  hosts: all
  become: True

  roles:

    - {role: geerlingguy.ruby, ruby_install_bundler: true, ruby_install_from_source: true, ruby_download_url: 'http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.3.tar.gz', ruby_version: 2.3.3 }


